"""add indexes and unique constraint to employees

Revision ID: 76d74e693f5a
Revises: b19cce1cae4c
Create Date: 2026-05-19 14:36:31.510393

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '76d74e693f5a'
down_revision: Union[str, Sequence[str], None] = 'b19cce1cae4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_hired_at'), 'employees', ['hired_at'], unique=False)
    op.create_unique_constraint('uq_employee_name_department', 'employees', ['full_name', 'department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_name_department', 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_hired_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    # ### end Alembic commands ###
